name: audio-to-midi
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - ffmpeg
  - libsndfile
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - attrs==24.2.0
      - audioread==3.0.1
      - basic-pitch==0.4.0
      - cattrs==24.1.2
      - certifi==2024.8.30
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - contourpy==1.3.0
      - coremltools==8.0
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - future==1.0.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.2
      - h5py==3.12.1
      - idna==3.10
      - joblib==1.4.2
      - jsonpickle==3.3.0
      - keras==3.6.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mido==1.3.2
      - mir-eval==0.7
      - ml-dtypes==0.4.1
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - music21==9.1.0
      - namex==0.0.8
      - numba==0.60.0
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.13.0
      - packaging==23.2
      - pillow==10.4.0
      - pooch==1.8.2
      - pretty-midi==0.2.10
      - protobuf==4.25.5
      - pyaml==24.9.0
      - pycparser==2.22
      - pyparsing==3.2.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - resampy==0.4.2
      - rich==13.9.2
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - sympy==1.13.3
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tqdm==4.66.5
      - urllib3==2.2.3
      - webcolors==24.8.0
      - werkzeug==3.0.4
      - wrapt==1.16.0
