name: data-tagging
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip=24.2
  - ipykernel=6.29.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - numpy=1.26.4
  - pandas=2.2.3
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - appdirs==1.4.4
      - asgiref==3.8.1
      - attrs==24.2.0
      - azure-core==1.32.0
      - azure-storage-blob==12.24.0
      - bleach==5.0.1
      - boto==2.49.0
      - boto3==1.35.66
      - botocore==1.35.66
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorama==0.4.6
      - cryptography==43.0.3
      - defusedxml==0.7.1
      - deprecated==1.2.15
      - django==4.2.16
      - django-annoying==0.10.6
      - django-cors-headers==3.6.0
      - django-csp==3.7
      - django-debug-toolbar==3.2.1
      - django-environ==0.10.0
      - django-extensions==3.2.3
      - django-filter==2.4.0
      - django-migration-linter==5.1.0
      - django-model-utils==4.1.1
      - django-ranged-fileresponse==0.1.2
      - django-rq==2.5.1
      - django-storages==1.12.3
      - django-user-agents==0.4.0
      - djangorestframework==3.15.2
      - drf-dynamic-fields==0.3.0
      - drf-flex-fields==0.9.5
      - drf-generators==0.3.0
      - google-api-core==2.23.0
      - google-api-python-client==2.154.0
      - google-auth==2.36.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-storage==2.18.2
      - httpcore==1.0.7
      - httpx==0.27.2
      - idna==3.10
      - ijson==3.3.0
      - inflection==0.5.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - keyboard==0.13.5
      - label-studio==1.14.0.post0
      - label-studio-sdk==1.0.7
      - lxml==5.3.0
      - nltk==3.9.1
      - openai==1.55.0
      - pillow==11.0.0
      - psycopg2-binary==2.9.10
      - pydantic==2.10.0
      - pyautogui==0.9.54
      - python-dateutil==2.9.0.post0
      - pytz==2022.7.1
      - pyyaml==6.0.2
      - redis==3.5.3
      - requests==2.32.3
      - rich==13.9.4
      - rq==1.10.1
      - sentry-sdk==2.18.0
      - sqlparse==0.5.2
      - tqdm==4.67.0
      - ujson==5.10.0
      - urllib3==1.26.20
      - xmljson==0.2.1
