name: segmenter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pip=24.2
  - numpy=1.23.5
  - scipy=1.10.1
  - matplotlib=3.6.3
  - pandas=2.0.3
  - scikit-learn=1.5.2
  - pip:
      - audioread==3.0.1
      - attrs==24.2.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - contourpy==1.0.7
      - cvxopt==1.3.2
      - cycler==0.12.1
      - decorator==5.1.1
      - enum34==1.1.10
      - fonttools==4.54.1
      - future==1.0.0
      - idna==3.10
      - importlib-resources==6.4.5
      - jams==0.3.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.9.2
      - llvmlite==0.41.1
      - mir-eval==0.7
      - msaf==0.1.80
      - msgpack==1.1.0
      - numba==0.58.0
      - packaging==24.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - pychorus==0.1
      - pycparser==2.22
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - referencing==0.35.1
      - requests==2.32.3
      - resampy==0.4.3
      - rpds-py==0.20.0
      - seaborn==0.13.2
      - six==1.16.0
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - threadpoolctl==3.5.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - vmo==0.30.5
      - zipp==3.20.2
